name: 'Unfurl Dropbox Screenshots'
description: 'Replaces Dropbox screenshot urls with markdown image links'
inputs:
  repo-token:  # id of input
    description: 'A GitHub access token with access to issues'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: link
  color: red
