name: Build

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build and test
    steps:

      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          npm i
          npm test

      - uses: JasonEtco/create-an-issue@v2
        id: create-issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Process Issues
        uses: ./ # Uses an action in the root directory
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
